aws_dbt_snowflake:
  outputs:
    dev:
      account: QYRKHMH-NO22147
      database: AIRBNB
      password: Leomessi@10msdhoni07
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: imsomax
      warehouse: COMPUTE_WH
  target: dev
